### ISSUE TITLE
Milestone sorting

### ISSUE THREAD

**Issue by davidhesselbom** [simonmika/IssuePanel#9]
I don't know how milestone sorting currently works (by date of creation, maybe?), but the current order for a certain project is
- Prototype 0.6
- Prototype 0.5
- Prototype 0.x
- Prototype 1.0
- Hack 1
- Prototype 1.x
- Later

which makes no sense. Sorting milestones alphabetically should result in something that makes a lot more sense.

**Comment by simonmika** [comment]
They are sorted by due date which makes totally sense.

**Comment by davidhesselbom** [comment]
Ah, you're right. Prototype 0.6 has no date, which is why it's out of order. Closing...
